# Generated by Django 6.1.1 on 2026-09-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=255)),
                ('merchant_normalized', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField()),
                ('account', models.CharField(max_length=10)),
                ('needs_review', models.BooleanField(default=True)),
            ],
        ),
    ]
