# Generated by Django 6.1.1 on 2026-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_activesession_transaction_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant_ambiguous',
            field=models.BooleanField(default=True),
        ),
    ]
